# Generated by Django 5.2.15 on 2026-06-25 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_ingestion_history"),
        ("supermarkets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawScrapedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("product_url", models.URLField(blank=True, max_length=500, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ingestionhistory",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="supermarkets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="ingestionhistory",
            name="supermarket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="supermarkets.supermarket",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("store_product_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "scraped_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store_name"], name="products_st_store_n_bd604c_idx"
                    )
                ],
                "unique_together": {("product", "store_name")},
            },
        ),
    ]
