# Generated by Codex on 2026-06-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rawscrapedproduct_product_created_at_product_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImportReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("possible_duplicate", "Possible duplicate"),
                            ("low_confidence_match", "Low-confidence match"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "store_name",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("scraped_product_name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "brand",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing product that may be a duplicate or needs admin review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_candidate_reviews",
                        to="products.product",
                    ),
                ),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product that the import linked to, when a match was accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_match_reviews",
                        to="products.product",
                    ),
                ),
                (
                    "raw_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_reviews",
                        to="products.rawscrapedproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "issue_type"], name="products_pr_status_c7bcac_idx"),
                    models.Index(fields=["store_name", "created_at"], name="products_pr_store_n_fe173a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raw_product", "issue_type", "candidate_product"),
                        name="unique_product_import_review_candidate",
                    )
                ],
            },
        ),
    ]
