# Generated by Codex on 2026-06-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_productimportreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="canonical_category",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="identity_key",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("store_name", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reviewed", "Reviewed"),
                            ("imported", "Imported"),
                            ("system", "System"),
                        ],
                        default="imported",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="products.product",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_name", "store_name"],
                "indexes": [
                    models.Index(fields=["normalized_name", "store_name"], name="products_pr_normali_168beb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalized_name", "store_name"),
                        name="unique_product_alias_name_store",
                    )
                ],
            },
        ),
    ]
